# Generated by Django 3.2.8 on 2021-12-08 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0019_portfolio_keycloak_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="approval_request_ref",
            field=models.CharField(
                default="",
                help_text="The ID of the approval submitted to approval-api",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="order",
            field=models.OneToOneField(
                help_text="The Order which the approval request belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.order",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The reason for the current state",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="request_completed_at",
            field=models.DateTimeField(
                editable=False,
                help_text="The time at which the approval request completed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("undecided", "Undecided"),
                    ("approved", "Approved"),
                    ("canceled", "Canceled"),
                    ("denied", "Denied"),
                    ("failed", "Failed"),
                ],
                default="undecided",
                editable=False,
                help_text=(
                    "The state of the approval request (approved, denied,"
                    " undecided, canceled, error)"
                ),
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="base_schema",
            field=models.JSONField(
                blank=True,
                help_text="JSON schema of the survey from the controller",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="create_json_schema",
            field=models.JSONField(
                blank=True,
                help_text="Current JSON schema for the service plan",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="imported",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Whether or not the service plan has been imported for"
                    " editing"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="modified",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether or not the service plan has a modified schema"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="modified_schema",
            field=models.JSONField(
                blank=True,
                help_text="Modified JSON schema for the service plan",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The name of the service plan",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="portfolio_item",
            field=models.ForeignKey(
                help_text="ID of the portfolio item",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.portfolioitem",
            ),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="service_offering_ref",
            field=models.CharField(
                help_text="Corresponding service offering from inventory-api",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="service_plan_ref",
            field=models.CharField(
                help_text="Corresponding service plan from inventory-api",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                blank=True, help_text="The image file", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(
                editable=False,
                help_text="The time at which the order completed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_request_sent_at",
            field=models.DateTimeField(
                editable=False,
                help_text=(
                    "The time at which the order request was sent to the"
                    " catalog inventory service"
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Canceled", "Canceled"),
                    ("Completed", "Completed"),
                    ("Created", "Created"),
                    ("Denied", "Denied"),
                    ("Failed", "Failed"),
                    ("Ordered", "Ordered"),
                ],
                default="Created",
                editable=False,
                help_text="Current state of the order",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                help_text="ID of the user who created this object",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="artifacts",
            field=models.JSONField(
                blank=True,
                help_text=(
                    "Contains a prefix-stripped key/value object that contains"
                    " all of the information exposed from product provisioning"
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="completed_at",
            field=models.DateTimeField(
                editable=False,
                help_text="The time at which the order item completed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="count",
            field=models.SmallIntegerField(
                default=0, editable=False, help_text="Item count"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text=(
                    "The external url of the service instance used with"
                    " relation to this order item"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="inventory_task_ref",
            field=models.CharField(
                help_text="Task reference from inventory-api",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="name",
            field=models.CharField(
                help_text="Name of the portfolio item or order process",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                help_text="The order that the order item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order_request_sent_at",
            field=models.DateTimeField(
                editable=False,
                help_text=(
                    "The time at which the order request was sent to the"
                    " catalog inventory service"
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="portfolio_item",
            field=models.ForeignKey(
                help_text="Stores the portfolio item ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.portfolioitem",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="provider_control_parameters",
            field=models.JSONField(
                blank=True,
                help_text=(
                    "The provider specific parameters needed to provision this"
                    " service. This might include namespaces, special keys."
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="service_instance_ref",
            field=models.CharField(
                help_text="Corresponding service instance from inventory-api",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="service_parameters",
            field=models.JSONField(
                blank=True,
                help_text="Sanitized JSON object with provisioning parameters",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="service_parameters_raw",
            field=models.JSONField(
                blank=True,
                help_text="Raw JSON object with provisioning parameters",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="service_plan_ref",
            field=models.CharField(
                help_text="Corresponding service plan from inventory-api",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="state",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Canceled", "Canceled"),
                    ("Completed", "Completed"),
                    ("Created", "Created"),
                    ("Denied", "Denied"),
                    ("Failed", "Failed"),
                    ("Ordered", "Ordered"),
                ],
                default="Created",
                editable=False,
                help_text="Current state of this order item",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="user",
            field=models.ForeignKey(
                help_text="ID of the user who created this object",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Describe the portfolio in details",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not this portfolio is enabled",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                help_text="ID of the icon image associated with this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="name",
            field=models.CharField(
                help_text="Portfolio name", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="owner",
            field=models.CharField(
                help_text="Name of the user who created the portfolio",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Description of the portfolio item",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="distributor",
            field=models.CharField(
                help_text="The name of the provider for the portfolio item",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="documentation_url",
            field=models.URLField(
                blank=True,
                help_text="The URL for documentation of the portfolio item",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="favorite",
            field=models.BooleanField(
                default=False,
                help_text="Definition of a favorate portfolio item",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                help_text="ID of the icon image associated with this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="long_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The longer description of the portfolio item",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="name",
            field=models.CharField(
                help_text="Name of the portfolio item", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="orphan",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Boolean if an associated service offering no longer"
                    " exists"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="portfolio",
            field=models.ForeignKey(
                help_text="ID of the parent portfolio",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="service_offering_ref",
            field=models.CharField(
                help_text=(
                    "The service offering this portfolio item was created from"
                ),
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="service_offering_source_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "The source reference this portfolio item was created from"
                ),
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="state",
            field=models.CharField(
                help_text="The current state of the portfolio item",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="support_url",
            field=models.URLField(
                blank=True,
                help_text="The URL for finding support for the portfolio item",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="progressmessage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="progressmessage",
            name="level",
            field=models.CharField(
                choices=[
                    ("Info", "Info"),
                    ("Error", "Error"),
                    ("Warning", "Warning"),
                    ("Debug", "Debug"),
                ],
                default="Info",
                editable=False,
                help_text="One of the predefined levels",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="progressmessage",
            name="message",
            field=models.TextField(
                blank=True, default="", help_text="The message content"
            ),
        ),
        migrations.AlterField(
            model_name="progressmessage",
            name="messageable_id",
            field=models.IntegerField(
                editable=False,
                help_text="ID of the order or order item",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="progressmessage",
            name="messageable_type",
            field=models.CharField(
                help_text=(
                    "Identify order or order item that this message belongs to"
                ),
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="progressmessage",
            name="received_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Message received at"
            ),
        ),
        migrations.AlterField(
            model_name="progressmessage",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="progressmessage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="serviceinstance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="serviceinstance",
            name="source",
            field=models.ForeignKey(
                help_text="ID of the source that this object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.source",
            ),
        ),
        migrations.AlterField(
            model_name="serviceinstance",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="serviceinstance",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="serviceinventory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="serviceinventory",
            name="source",
            field=models.ForeignKey(
                help_text="ID of the source that this object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.source",
            ),
        ),
        migrations.AlterField(
            model_name="serviceinventory",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="serviceinventory",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="serviceoffering",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="serviceoffering",
            name="source",
            field=models.ForeignKey(
                help_text="ID of the source that this object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.source",
            ),
        ),
        migrations.AlterField(
            model_name="serviceoffering",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="serviceoffering",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="serviceofferingnode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="serviceofferingnode",
            name="source",
            field=models.ForeignKey(
                help_text="ID of the source that this object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.source",
            ),
        ),
        migrations.AlterField(
            model_name="serviceofferingnode",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="serviceofferingnode",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="serviceplan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="serviceplan",
            name="source",
            field=models.ForeignKey(
                help_text="ID of the source that this object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.source",
            ),
        ),
        migrations.AlterField(
            model_name="serviceplan",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="serviceplan",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(
                help_text="Name of the source", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="taglink",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="taglink",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="taglink",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="external_tenant",
            field=models.CharField(
                help_text="User's account number", max_length=32, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object was created",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="tenant",
            field=models.ForeignKey(
                help_text="ID of the tenant the object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object was last updated",
            ),
        ),
    ]
