# Generated by Django 3.2.9 on 2022-02-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_source_last_refresh_task_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="share_count",
            field=models.IntegerField(
                default=0,
                help_text=(
                    "The number of different groups sharing this portfolio"
                ),
            ),
        ),
    ]
