# Generated by Django 4.0.2 on 2022-04-01 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_seed_email_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="process_method",
        ),
        migrations.RemoveField(
            model_name="template",
            name="process_setting",
        ),
        migrations.RemoveField(
            model_name="template",
            name="signal_method",
        ),
        migrations.RemoveField(
            model_name="template",
            name="signal_setting",
        ),
        migrations.DeleteModel("Notification"),
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_type",
                    models.CharField(
                        help_text="Name of the notification type",
                        max_length=128,
                    ),
                ),
                (
                    "setting_schema",
                    models.JSONField(
                        blank=True,
                        help_text="JSON schema of the notification type",
                        null=True,
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "ID of the icon image associated with this object"
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time at which the object was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            "The time at which the object was last updated"
                        ),
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the notification method",
                        max_length=128,
                    ),
                ),
                (
                    "settings",
                    models.TextField(
                        blank=True,
                        help_text="Encrypted settings",
                        null=True,
                    ),
                ),
                (
                    "notification_type",
                    models.ForeignKey(
                        help_text="ID of the notification type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.notificationtype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="ID of the tenant the object belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="template",
            name="process_method",
            field=models.ForeignKey(
                help_text=(
                    "ID of the notification method for processing the workflow"
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="process_notification",
                to="main.notificationsetting",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="signal_method",
            field=models.ForeignKey(
                help_text=(
                    "ID of the notification method for signaling the "
                    "completion of the workflow",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signal_notification",
                to="main.notificationsetting",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationtype",
            constraint=models.CheckConstraint(
                check=models.Q(("n_type__length__gt", 0)),
                name="main_notificationtype_n_type_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationtype",
            constraint=models.UniqueConstraint(
                fields=("n_type",), name="main_notificationtype_n_type_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationsetting",
            constraint=models.CheckConstraint(
                check=models.Q(("name__length__gt", 0)),
                name="main_notificationsetting_name_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationsetting",
            constraint=models.UniqueConstraint(
                fields=("name", "tenant"),
                name="main_notificationsetting_name_unique",
            ),
        ),
    ]
