# Generated by Django 4.0.2 on 2022-04-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            (
                "0041_alter_notificationsetting_settings_alter_order_state_"
                "and_more"
            ),
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("Approval Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Canceled", "Canceled"),
                    ("Completed", "Completed"),
                    ("Created", "Created"),
                    ("Denied", "Denied"),
                    ("Failed", "Failed"),
                    ("Ordered", "Ordered"),
                ],
                default="Created",
                editable=False,
                help_text="Current state of the order",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="state",
            field=models.CharField(
                choices=[
                    ("Approval Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Canceled", "Canceled"),
                    ("Completed", "Completed"),
                    ("Created", "Created"),
                    ("Denied", "Denied"),
                    ("Failed", "Failed"),
                    ("Ordered", "Ordered"),
                ],
                default="Created",
                editable=False,
                help_text="Current state of this order item",
                max_length=20,
            ),
        ),
    ]
