# Generated by Django 3.2.5 on 2022-04-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_alter_order_state_alter_orderitem_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="refresh_state",
            field=models.CharField(
                choices=[
                    ("Done", "Done"),
                    ("InProgress", "Inprogress"),
                    ("Failed", "Failed"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                editable=False,
                help_text="State of current refresh",
                max_length=32,
            ),
        ),
    ]
