# Generated by Django 4.0.2 on 2022-05-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0043_alter_source_refresh_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioitem",
            name="name",
            field=models.CharField(
                help_text="Name of the portfolio item", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="serviceoffering",
            name="name",
            field=models.CharField(max_length=512),
        ),
    ]
