# Generated by Django 4.0.3 on 2022-05-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0047_rename_default_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="error_code",
            field=models.IntegerField(
                choices=[(0, "Success"), (1, "Failed"), (2, "Bounded Source")],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="error_dict",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores error args used by localization",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="last_refresh_stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The result stats for the last source refresh",
            ),
        ),
    ]
