# Generated by Django 4.0.2 on 2022-05-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_notificationsetting_encryption"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationtype",
            name="main_notificationtype_n_type_unique",
        ),
        migrations.AlterField(
            model_name="notificationtype",
            name="n_type",
            field=models.CharField(
                help_text="Name of the notification type",
                max_length=128,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="name",
            field=models.CharField(
                help_text="Name of the portfolio item or order process",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="name",
            field=models.CharField(help_text="Portfolio name", max_length=255),
        ),
    ]
