# Generated by Django 4.0.2 on 2022-06-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0051_progressmessage_message_params"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workflow",
            options={"ordering": ["internal_sequence"]},
        ),
        migrations.AlterField(
            model_name="workflow",
            name="internal_sequence",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
