# Generated by Django 3.2.5 on 2021-09-28 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_auto_20210914_2122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subrequests",
                to="main.request",
            ),
        ),
    ]
