# Generated by Django 3.2.5 on 2021-10-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_request_parent"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="catalogserviceplan",
            name="main_catalogserviceplan_name_empty",
        ),
        migrations.RemoveConstraint(
            model_name="catalogserviceplan",
            name="main_catalogserviceplan_name_unique",
        ),
        migrations.RenameField(
            model_name="catalogserviceplan",
            old_name="base",
            new_name="base_schema",
        ),
        migrations.RemoveField(
            model_name="catalogserviceplan",
            name="description",
        ),
        migrations.AddField(
            model_name="catalogserviceplan",
            name="create_json_schema",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="catalogserviceplan",
            name="imported",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="catalogserviceplan",
            name="modified_schema",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="catalogserviceplan",
            name="service_offering_ref",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="catalogserviceplan",
            name="service_plan_ref",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="modified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
