# Generated by Django 3.2.5 on 2021-10-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_auto_20211004_2054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogserviceplan",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
