# Generated by Django 3.2.8 on 2021-11-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_auto_20211102_2131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="operation",
            field=models.CharField(
                choices=[
                    ("notify", "Notify"),
                    ("start", "Start"),
                    ("skip", "Skip"),
                    ("memo", "Memo"),
                    ("approve", "Approve"),
                    ("deny", "Deny"),
                    ("cancel", "Cancel"),
                    ("error", "Error"),
                ],
                default="memo",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="decision",
            field=models.CharField(
                choices=[
                    ("undecided", "Undecided"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                    ("canceled", "Canceled"),
                    ("error", "Error"),
                ],
                default="undecided",
                editable=False,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("skipped", "Skipped"),
                    ("started", "Started"),
                    ("notified", "Notified"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("failed", "Failed"),
                ],
                default="pending",
                editable=False,
                max_length=10,
            ),
        ),
    ]
