# Generated by Django 3.2.8 on 2021-11-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_auto_20211102_2131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="comments",
            field=models.TextField(
                blank=True, help_text="Comments for the action"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="operation",
            field=models.CharField(
                choices=[
                    ("Notify", "Notify"),
                    ("Start", "Start"),
                    ("Skip", "Skip"),
                    ("Memo", "Memo"),
                    ("Approve", "Approve"),
                    ("Deny", "Deny"),
                    ("Cancel", "Cancel"),
                    ("Error", "Error"),
                ],
                default="Memo",
                help_text="Action type, must be one of the predefined values. The request state will be updated according to the operation.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="request",
            field=models.ForeignKey(
                help_text="ID of the request that the action belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="main.request",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="decision",
            field=models.CharField(
                choices=[
                    ("Undecided", "Undecided"),
                    ("Approved", "Approved"),
                    ("Denied", "Denied"),
                    ("Canceled", "Canceled"),
                    ("Error", "Error"),
                ],
                default="Undecided",
                editable=False,
                help_text="Approval decision, must be one of the predefined values",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="description",
            field=models.TextField(
                blank=True, help_text="Describe the request in more details"
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="finished_at",
            field=models.DateTimeField(
                editable=False,
                help_text="Time when the request was finished (skipped, canceled, or completed)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="group_name",
            field=models.CharField(
                editable=False,
                help_text="Name of approver group(s) assigned to approve this request",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="name",
            field=models.CharField(
                help_text="Name of the request to be created", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="notified_at",
            field=models.DateTimeField(
                editable=False,
                help_text="Time when a notification was sent to approvers",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="number_of_children",
            field=models.SmallIntegerField(
                default=0, editable=False, help_text="Number of child requests"
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="number_of_finished_children",
            field=models.SmallIntegerField(
                default=0,
                editable=False,
                help_text="Number of finished child requests",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="parent",
            field=models.ForeignKey(
                help_text="ID of the parent group if present",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subrequests",
                to="main.request",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="reason",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="Optional reason for the decision, present normally when the decision is denied",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="state",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Skipped", "Skipped"),
                    ("Started", "Started"),
                    ("Notified", "Notified"),
                    ("Completed", "Completed"),
                    ("Canceled", "Canceled"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                editable=False,
                help_text="The state of the request, must be one of the predefined values",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="workflow",
            field=models.ForeignKey(
                help_text="ID of the workflow that the request belongs to. Present only if the request is a leaf node",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.workflow",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Describe the template with more details",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="title",
            field=models.CharField(
                help_text="Name of the template", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Describe the workflow in more details",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="group_refs",
            field=models.JSONField(
                default=list,
                help_text="Array of RBAC groups associated with workflow. The groups need to have approval permission",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="name",
            field=models.CharField(
                help_text="Name of the workflow", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="template",
            field=models.ForeignKey(
                help_text="ID of the template that the workflow belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.template",
            ),
        ),
    ]
