# Generated by Django 3.2.8 on 2021-11-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalrequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("undecided", "Undecided"),
                    ("approved", "Approved"),
                    ("canceled", "Canceled"),
                    ("denied", "Denied"),
                    ("failed", "Failed"),
                ],
                default="undecided",
                editable=False,
                max_length=10,
            ),
        ),
    ]
