# Generated by Django 3.2.5 on 2021-12-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_auto_20211208_2019"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServicePlan",
            new_name="InventoryServicePlan",
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="favorite",
            field=models.BooleanField(
                default=False,
                help_text="Definition of a favorite portfolio item",
            ),
        ),
    ]
