# Generated by Django 3.2.5 on 2021-12-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_auto_20211214_1529"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogserviceplan",
            name="changed",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not the service plan has been changed",
            ),
        ),
        migrations.AddField(
            model_name="catalogserviceplan",
            name="changed_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The message for the changed service plan",
            ),
        ),
    ]
