# Generated by Django 3.2.8 on 2021-12-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_inventoryserviceplan_schema_sha256"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CatalogServicePlan",
            new_name="ServicePlan",
        ),
        migrations.RemoveIndex(
            model_name="serviceplan",
            name="main_catalo_tenant__4b1542_idx",
        ),
        migrations.AddIndex(
            model_name="serviceplan",
            index=models.Index(
                fields=["tenant", "portfolio_item"],
                name="main_servic_tenant__bd89da_idx",
            ),
        ),
    ]
