# Generated by Django 3.2.8 on 2021-12-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_auto_20211215_1927"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="serviceplan",
            name="main_servic_tenant__bd89da_idx",
        ),
        migrations.RemoveField(
            model_name="serviceplan",
            name="create_json_schema",
        ),
        migrations.RemoveField(
            model_name="serviceplan",
            name="imported",
        ),
        migrations.RemoveField(
            model_name="serviceplan",
            name="modified",
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="outdated",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Whether or not the base schema is outdated. The portfolio item is not orderable if the base schema is outdated.",
            ),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="outdated_changes",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                help_text="Changes of the base schema from inventory since last edit",
            ),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="base_sha256",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                help_text="SHA256 of the base schema",
            ),
        ),
    ]
