# Generated by Django 3.2.5 on 2022-01-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_auto_20211215_2027"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="availability_message",
            field=models.TextField(
                blank=True,
                default="Unavailable",
                help_text="The message about the source availability",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="availability_status",
            field=models.TextField(
                blank=True,
                default="unavailable",
                help_text="The status for the source availability status",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="last_available_at",
            field=models.DateTimeField(
                editable=False,
                help_text="The time at which the source was available",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="last_checked_at",
            field=models.DateTimeField(
                editable=False,
                help_text="The time at which the source was checked availability",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="refresh_state",
            field=models.CharField(
                choices=[
                    ("Done", "Done"),
                    ("Failed", "Failed"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                editable=False,
                help_text="State of current refresh",
                max_length=10,
            ),
        ),
    ]
