# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "generic/centos8"
  #config.vm.box = "centos/8"
  config.vm.box = "generic/rhel8"

  config.vm.synced_folder "./data", "/vagrant_data"

  config.vm.define "keycloak" do |this|
    this.vm.hostname="keycloak"
    this.vm.network :private_network, ip: "192.168.33.20"
    this.vm.provision "shell", path: "keycloak_install.sh"
  end

  config.vm.define "catalog" do |this|
    this.vm.synced_folder "../..", "/src"
    this.vm.hostname="catalog"
    this.vm.network :private_network, ip: "192.168.33.21"
    this.vm.provision "shell", path: "catalog_install.sh"
  end

  config.vm.define "nginx" do |this|
    this.vm.hostname="nginx"
    this.vm.network :private_network, ip: "192.168.33.22"
    this.vm.provision "shell", path: "nginx_install.sh"
  end
end
