title = "Pinakes Gitleaks Config"

[allowlist]
description = "Allowlist"
regexes = [
    '''SOMESECRETVALUE''',
    '''settings\.KEYCLOAK_CLIENT_SECRET''',
    '''VEVTVFRFU1RURVNUVEVTVFRFU1RURVNUVEVTVFRFU1Q=''',
]
paths = [
    '''tools.*\.key'''
]
