apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      initContainers:
        - name: init-keycloak
          image: busybox
          command:
          - sh
          - -c
          - 'while true; do echo "Waiting for keycloak service to come up..."; wget http://keycloak:8080 -q -T 1 -O /dev/null >/dev/null 2>/dev/null && break; sleep 1; done; echo "Service is up! Starting main container."'
      containers:
        - env:
            - name: CATALOG_LOG_ROOT
              value: /tmp
            - name: KEYCLOAK_URL
              value: http://keycloak:8080/auth
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: REDIRECT_URIS_STR
              value: http://app:8000,http://app:8000/*,*
            - name: CONTROLLER_VERIFY_SSL
              value: "False"
            - name: DJANGO_SETTINGS_MODULE
              value: ansible_catalog.settings.development
          image: localhost/ansible-catalog
          imagePullPolicy: Never
          name: app
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: app-claim0
      volumes:
        - name: app-claim0
          persistentVolumeClaim:
            claimName: app-claim0
status: {}
