version: '3'

services:
  app:
    image: ansible-catalog:dev
    build:
      context: ../../
      dockerfile: tools/docker-compose/images/app/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - "../../:/tmp/app:z"
    environment:
      - DJANGO_SETTINGS_MODULE=ansible_catalog.settings.development
      - CATALOG_LOG_ROOT=/tmp/app
      - CONTROLLER_VERIFY_SSL=False
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - REDIRECT_URIS_STR=http://app:8000,http://app:8000/*,*
    depends_on: 
      - keycloak-setup

  keycloak-setup:
    image: keycloak-setup
    build:
      context: ../../
      dockerfile: tools/docker-compose/images/keycloak-setup/Dockerfile
    volumes:
      - "../../:/tmp/app:z"
    environment:
      - DJANGO_SETTINGS_MODULE=ansible_catalog.settings.development
      - CATALOG_LOG_ROOT=/tmp/app
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
      - ANSIBLE_CATALOG_REDIS_HOST=redis
      - CONTROLLER_VERIFY_SSL=False
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - REDIRECT_URIS_STR=http://app:8000,http://app:8000/*,*
    depends_on: 
    - keycloak

  worker:
    image: ansible-catalog:dev
    environment:
      - DJANGO_SETTINGS_MODULE=ansible_catalog.settings.development
      - CATALOG_LOG_ROOT=/tmp/app
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
      - ANSIBLE_CATALOG_REDIS_HOST=redis
      - CONTROLLER_VERIFY_SSL=False
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - REDIRECT_URIS_STR=http://app:8000,http://app:8000/*,*
    volumes:
      - "../../:/tmp/app:z"
    depends_on:
      - app
      - redis
    command: python manage.py rqworker default

  keycloak:
    image: 'quay.io/keycloak/keycloak:15.0.2'
    environment:
      - 'DB_VENDOR=postgres'
      - 'DB_ADDR=postgres'
      - 'DB_DATABASE=keycloak'
      - 'DB_USER=keycloak'
      - 'DB_PASSWORD=password'
      - 'KEYCLOAK_USER=admin'
      - 'KEYCLOAK_PASSWORD=admin'
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  postgres:
    image: 'postgres:13-alpine'
    environment:
      - 'POSTGRES_USER=keycloak'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=keycloak'
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

volumes:
  pg_data: {}
