apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-setup
spec:
  template:
    spec:
      containers:
      - name: keycloak-setup
        image: localhost/pinakes
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: pinakes-env-overrides
        command:  [/opt/app-root/src/tools/docker/scripts/keycloak-setup.sh]
      restartPolicy: Never
  backoffLimit: 1
