apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - env:
            - name: DB_ADDR
              value: postgres
            - name: DB_DATABASE
              value: keycloak
            - name: DB_PASSWORD
              value: password
            - name: DB_USER
              value: keycloak
            - name: DB_VENDOR
              value: postgres
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: JDBC_PARAMS
              value: sslmode=verify-ca&sslrootcert=/etc/ssl_config/root.crt
            - name: KEYCLOAK_USER
              value: admin
          args: ['-Dkeycloak.frontendUrl=https://keycloak.k8s.local/auth']
          image: quay.io/keycloak/keycloak:15.0.2
          name: keycloak
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /etc/ssl_config
              name: ssl
            - mountPath: /opt/jboss/keycloak/themes/pinakes
              name: themes
      restartPolicy: Always
      volumes:
        - name: ssl
          configMap:
            name: postgresql
            items:
              - key: "root.crt"
                path: "root.crt"
                mode: 0640
        - name: themes
          configMap:
            name: keycloak-theme
            items:
              - key: "theme.properties"
                path: "./login/theme.properties"
                mode: 0640
              - key: "styles.css"
                path: "./login/resources/css/styles.css"
                mode: 0640
              - key: "background.png"
                path: "./login/resources/img/background.png"
                mode: 0640
status: {}
