# Generated by Django 3.2.5 on 2021-08-05 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='')),
                ('source_ref', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={},
        ),
        migrations.AlterField(
            model_name='action',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='main.request'),
        ),
        migrations.AlterField(
            model_name='request',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_requests', to='main.request'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image'),
        ),
    ]
