# Generated by Django 3.2.5 on 2021-08-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20210805_1656"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("source_ref", models.CharField(default="", max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name="portfolio",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.image",
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.image",
            ),
        ),
    ]
