# Generated by Django 3.2.5 on 2021-09-14 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_auto_20210903_1437"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="inventory_task_ref",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="service_instance_ref",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="service_plan_ref",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="service_offering_ref",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.CreateModel(
            name="CatalogServicePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("base", models.JSONField(blank=True, null=True)),
                ("modified", models.JSONField(blank=True, null=True)),
                (
                    "portfolio_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.portfolioitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="catalogserviceplan",
            index=models.Index(
                fields=["tenant", "portfolio_item"],
                name="main_catalo_tenant__4b1542_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogserviceplan",
            constraint=models.CheckConstraint(
                check=models.Q(("name__length__gt", 0)),
                name="main_catalogserviceplan_name_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogserviceplan",
            constraint=models.UniqueConstraint(
                fields=("name", "tenant", "portfolio_item"),
                name="main_catalogserviceplan_name_unique",
            ),
        ),
    ]
