# Generated by Django 3.2.4 on 2021-06-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_created_at', models.DateTimeField()),
                ('source_updated_at', models.DateTimeField()),
                ('source_ref', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('extra', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_created_at', models.DateTimeField()),
                ('source_updated_at', models.DateTimeField()),
                ('source_ref', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('survey_enabled', models.BooleanField(default=False)),
                ('kind', models.IntegerField(choices=[(0, 'JobTemplate'), (1, 'Workflow')], default=0)),
                ('extra', models.JSONField()),
                ('service_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.serviceinventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_tenant', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_created_at', models.DateTimeField()),
                ('source_updated_at', models.DateTimeField()),
                ('source_ref', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('extra', models.JSONField()),
                ('create_json_schema', models.JSONField()),
                ('update_json_schema', models.JSONField(null=True)),
                ('service_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.serviceoffering')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.source')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOfferingNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_created_at', models.DateTimeField()),
                ('source_updated_at', models.DateTimeField()),
                ('source_ref', models.CharField(max_length=32)),
                ('extra', models.JSONField()),
                ('root_service_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_service_offering', to='inventory.serviceoffering')),
                ('service_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.serviceinventory')),
                ('service_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.serviceoffering')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.source')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.source'),
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tenant'),
        ),
        migrations.AddField(
            model_name='serviceinventory',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.source'),
        ),
        migrations.AddField(
            model_name='serviceinventory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tenant'),
        ),
    ]
