# Generated by Django 3.2.5 on 2021-07-19 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('context', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('process_setting', models.JSONField(blank=True, null=True)),
                ('signal_setting', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_tenant', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('group_refs', models.JSONField(default=list)),
                ('internal_sequence', models.DecimalField(db_index=True, decimal_places=6, max_digits=16)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.template')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.tenant'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('Pending', 'Pending'), ('Skipped', 'Skipped'), ('Started', 'Started'), ('Notified', 'Notified'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Failed', 'Failed')], default='Pending', editable=False, max_length=10)),
                ('decision', models.CharField(choices=[('Undecided', 'Undecided'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Canceled', 'Canceled'), ('Error', 'Error')], default='Undecided', editable=False, max_length=10)),
                ('reason', models.TextField(blank=True, editable=False)),
                ('process_ref', models.CharField(editable=False, max_length=128)),
                ('group_name', models.CharField(editable=False, max_length=128)),
                ('group_ref', models.CharField(db_index=True, editable=False, max_length=128)),
                ('notified_at', models.DateTimeField(editable=False, null=True)),
                ('finished_at', models.DateTimeField(editable=False, null=True)),
                ('number_of_children', models.SmallIntegerField(default=0, editable=False)),
                ('number_of_finished_children', models.SmallIntegerField(default=0, editable=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.request')),
                ('request_context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.requestcontext')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('Notify', 'Notify'), ('Start', 'Start'), ('Skip', 'Skip'), ('Memo', 'Memo'), ('Approve', 'Approve'), ('Deny', 'Deny'), ('Cancel', 'Cancel'), ('Error', 'Error')], default='Memo', max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.request')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(check=models.Q(('name__length__gt', 0)), name='approval_workflow_name_empty'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('name', 'tenant', 'template'), name='approval_workflow_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('internal_sequence', 'tenant'), name='approval_workflow_internal_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.CheckConstraint(check=models.Q(('title__length__gt', 0)), name='approval_template_title_empty'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('title', 'tenant'), name='approval_template_title_unique'),
        ),
    ]
