# Generated by Django 3.2.4 on 2021-06-29 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('context', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='action',
            name='operation',
            field=models.CharField(choices=[('Notify', 'Notify'), ('Start', 'Start'), ('Skip', 'Skip'), ('Memo', 'Memo'), ('Approve', 'Approve'), ('Deny', 'Deny'), ('Cancel', 'Cancel'), ('Error', 'Error')], default='Memo', max_length=10),
        ),
        migrations.AddField(
            model_name='action',
            name='processed_by',
            field=models.CharField(default='', editable=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='approval.request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='decision',
            field=models.CharField(choices=[('Undecided', 'Undecided'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Canceled', 'Canceled'), ('Error', 'Error')], default='Undecided', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='request',
            name='finished_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='group_name',
            field=models.CharField(default='', editable=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='group_ref',
            field=models.CharField(db_index=True, default='', editable=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='notified_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='number_of_children',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='request',
            name='number_of_finished_children',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='request',
            name='owner',
            field=models.CharField(default='', editable=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.request'),
        ),
        migrations.AddField(
            model_name='request',
            name='process_ref',
            field=models.CharField(default='', editable=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.workflow'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.TextField(blank=True, default='', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='requester_name',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Skipped', 'Skipped'), ('Started', 'Started'), ('Notified', 'Notified'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Failed', 'Failed')], default='Pending', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='internal_sequence',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=16),
        ),
        migrations.AddField(
            model_name='request',
            name='request_context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.requestcontext'),
        ),
    ]
