# Generated by Django 3.2.5 on 2021-07-15 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approval', '0002_auto_20210629_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={},
        ),
        migrations.RemoveField(
            model_name='action',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='request',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='request',
            name='requester_name',
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
