# Generated by Django 3.2.5 on 2021-08-05 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={},
        ),
        migrations.AlterModelOptions(
            name="portfolio",
            options={},
        ),
        migrations.AlterModelOptions(
            name="portfolioitem",
            options={},
        ),
        migrations.AlterField(
            model_name="action",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="main.request",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_requests",
                to="main.request",
            ),
        ),
    ]
