# Generated by Django 3.2.5 on 2021-08-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_auto_20210818_1530"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app_name", models.CharField(editable=False, max_length=128)),
                ("tag_name", models.CharField(editable=False, max_length=128)),
                (
                    "object_type",
                    models.CharField(editable=False, max_length=32),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.tenant",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.workflow",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="taglink",
            constraint=models.UniqueConstraint(
                fields=("app_name", "object_type", "tenant", "workflow"),
                name="main_taglink_tag_unique",
            ),
        ),
    ]
