# Generated by Django 3.2.8 on 2021-11-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_catalogserviceplan_imported"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceinstance",
            name="source_created_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="serviceinstance",
            name="source_updated_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="serviceinventory",
            name="source_created_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="serviceinventory",
            name="source_updated_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="serviceoffering",
            name="source_created_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="serviceoffering",
            name="source_updated_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="serviceofferingnode",
            name="source_created_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="serviceofferingnode",
            name="source_updated_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="serviceplan",
            name="source_created_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="serviceplan",
            name="source_updated_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
