# Generated by Django 3.2.5 on 2021-11-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_auto_20211108_1729"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="portfolioitem",
            name="main_portfolioitem_name_unique",
        ),
    ]
