# Generated by Django 3.2.7 on 2021-11-16 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_remove_portfolioitem_main_portfolioitem_name_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("path", models.TextField()),
                ("last_sync_time", models.DateTimeField()),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgroups",
                        to="main.group",
                    ),
                ),
            ],
        ),
    ]
