# Generated by Django 3.2.8 on 2022-01-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_auto_20220114_1950"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="keycloak_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
