# Generated by Django 3.2.4 on 2021-07-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210714_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='owner',
        ),
    ]
