---
- hosts: localhost
  vars:
    verify_keycloak_ssl: false
    seed_keycloak: true
    seed_groups:
      - name: Information Technology - Sample
        clientRoles:
          - catalog-admin
          - approval-admin
      - name: Marketing - Sample
        clientRoles:
          - catalog-user
          - approval-user
      - name: Finance - Sample
        clientRoles:
          - approval-approver
    seed_users:
      - username: fred.sample
        firstName: Fred
        lastName: Sample
        email: fred@example.com
        enabled: true
        credentials:
          - type: "password"
            value: "fred"
        groups:
          - Information Technology - Sample
      - username: barney.sample
        firstName: Barney
        lastName: Sample
        email: barney@example.com
        enabled: true
        credentials:
          - type: "password"
            value: "barney"
        groups:
          - Marketing - Sample
      - username: wilma.sample
        firstName: Wilma
        lastName: Sample
        email: wilma@example.com
        enabled: true
        credentials:
          - type: "password"
            value: "wilma"
        groups:
          - Finance - Sample
  roles:
    - mkanoor.catalog_keycloak.setup
